dist: trusty
language: bash
sudo: required

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-engine
  - docker version

install:
  #- docker build --squash --build-arg BUILD_DATE=`date -u +"%Y-%m-%d_%H:%M:%SZ"` --build-arg VCS_REF=`git rev-parse --short HEAD` -t stlouisn/$DOCKER_IMAGE .
  - docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%d_%H:%M:%SZ"` --build-arg VCS_REF=`git rev-parse --short HEAD` -t stlouisn/$DOCKER_IMAGE .

before_script:
  - docker run -d --name $DOCKER_IMAGE stlouisn/$DOCKER_IMAGE

script:
  - docker ps | grep -q stlouisn/$DOCKER_IMAGE

after_success:
  - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker push stlouisn/$DOCKER_IMAGE:latest;
    else
      docker push stlouisn/$DOCKER_IMAGE:$TRAVIS_BRANCH;
    fi
