dist: xenial
group: travis_latest

if: |
  branch = master AND ! commit_message =~ /readme.md/ AND ! commit_message =~ /docker-compose.yml/
  OR type = cron

language: bash
sudo: required

services:
  - docker

env:

  global:
    - BUILD_DATE="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    - BUILD_NUMBER="${TRAVIS_BUILD_NUMBER}"
    - DOCKER_DESCRIPTION="web-based media streaming"
    - DOCKER_MAINTAINER="stlouisn"
    - DOCKER_NAME="airsonic"
    - DOCKER_URL="https://airsonic.github.io/"
    - SCHEMA_VERSION="1.0"
    - UBUNTU_CODENAME="$(curl -ksSL https://raw.githubusercontent.com/tianon/docker-brew-ubuntu-core/master/rolling)"
    - VCS_REF="$(git rev-parse --short HEAD)"
    - VCS_URL="$(git remote get-url origin | head -c-5)"

  matrix:
    - DOCKER_TAG="latest"
      DOCKER_VERSION="$(curl -s https://airsonic.github.io/download/ | grep 'airsonic.war' | head -n 1 | awk -F '/v' {'print $2'} | awk -F '/' {'print $1'})"

before_install:
  - sudo /sbin/sysctl -w net.ipv4.conf.all.forwarding=1
  - sudo bash travis/docker.sh
  - sudo docker version

install:
  - sudo docker run --privileged linuxkit/binfmt:v0.7
  - sudo docker run --privileged -d -p 1234:1234 --name buildkit moby/buildkit:latest --addr tcp://0.0.0.0:1234 --oci-worker-platform linux/arm --oci-worker-platform linux/armhf --oci-worker-platform linux/arm64 --oci-worker-platform linux/amd64
  - sudo docker cp buildkit:/usr/bin/buildctl /usr/bin/
  - export BUILDKIT_HOST=tcp://0.0.0.0:1234

before_script:
  - sed -i -e '/^$/d' -e 's/^[ \t]*//' -e '/^#/d' docker/Dockerfile*
  - chmod 0544 rootfs/usr/local/bin/docker_entrypoint.sh
  - mkdir -p ./userfs/Airsonic
  - curl -ksSL -o airsonic.war "https://github.com/airsonic/airsonic/releases/download/v${DOCKER_VERSION}/airsonic.war"

  - mkdir -p ./userfs/usr/lib/airsonic
  - curl -L -o ./userfs/usr/lib/airsonic/airsonic.war ${DOWNLOAD_URL}
      DOWNLOAD_URL=

script:
  - >
    docker build
    --label org.label-schema.build-date="${BUILD_DATE}"
    --label org.label-schema.build-number="${BUILD_NUMBER}"
    --label org.label-schema.description="${DOCKER_DESCRIPTION}"
    --label org.label-schema.maintainer="${DOCKER_MAINTAINER}"
    --label org.label-schema.name="${DOCKER_NAME}"
    --label org.label-schema.url="${DOCKER_URL}"
    --label org.label-schema.version="${DOCKER_VERSION}"
    --label org.label-schema.schema-version="${SCHEMA_VERSION}"
    --label org.label-schema.vcs-ref="${VCS_REF}"
    --label org.label-schema.vcs-url="${VCS_URL}"
    --tag ${DOCKER_USERNAME}/${DOCKER_NAME}:${DOCKER_TAG}
    --pull .

after_success:
  - echo ${DOCKER_PASSWORD} | docker login --username ${DOCKER_USERNAME} --password-stdin
  - docker push ${DOCKER_USERNAME}/${DOCKER_NAME}:${DOCKER_TAG}

notifications:
  email:
    on_success: never
    on_failure: change
