language: bash
dist: trusty
group: travis_latest
sudo: required

addons:
  apt:
    packages:
      - docker-ce

branches:
  only:
    - master

env:
  global:
    - BUILD_DATE="`date -u +%Y-%m-%dT%H:%M:%SZ`"
    - BUILD_NUMBER="$TRAVIS_BUILD_NUMBER"
    - DISTRIB_ID="`(docker pull stlouisn/ubuntu:rolling && docker run -it --rm stlouisn/ubuntu:rolling /bin/bash -c 'cat /etc/lsb-release') | grep DISTRIB_ID | awk -F '=' {'print $2'}`"
    - DISTRIB_RELEASE="`(docker pull stlouisn/ubuntu:rolling && docker run -it --rm stlouisn/ubuntu:rolling /bin/bash -c 'cat /etc/lsb-release') | grep DISTRIB_RELEASE | awk -F '=' {'print $2'}`"
    - DISTRIB_CODENAME="`(docker pull stlouisn/ubuntu:rolling && docker run -it --rm stlouisn/ubuntu:rolling /bin/bash -c 'cat /etc/lsb-release') | grep DISTRIB_CODENAME | awk -F '=' {'print $2'}`"
    - DOCKER_DESCRIPTION="web-based media streaming"
    - DOCKER_MAINTAINER="stlouisn"
    - DOCKER_NAME="airsonic"
    - DOCKER_URL="https://airsonic.github.io/"
    - SCHEMA_VERSION="1.0"
    - VCS_REF="`git rev-parse --short HEAD`"
    - VCS_URL="`git remote get-url origin | head -c-5`"
  matrix:
    - DOCKER_TAG="latest"
      DOCKER_VERSION="`curl -s https://airsonic.github.io/download/ | grep 'airsonic.war' | head -n 1 | awk -F '/v' {'print $2'} | awk -F '/' {'print $1'}`"
      DOWNLOAD_URL="https://github.com/airsonic/airsonic/releases/download/v{$DOCKER_VERSION}/airsonic.war"

before_install:
  - docker version

install:
  #- docker run -it --name build stlouisn/build:dev /bin/bash -c 'git clone https://github.com/airsonic/airsonic.git /build; cd /build; mvn clean package -DskipTests=true -Dmaven.javadoc.skip=true -B -V'
  #- docker cp build:/build/airsonic-main/target/airsonic.war ./rootfs/usr/lib/airsonic/.
  #- chown ./rootfs/
  - curl -L $DOWNLOAD_URL -o ./rootfs/usr/lib/airsonic/airsonic.war && \
  #########
  #- sudo add-apt-repository -y ppa:jonathonf/openjdk
  #- sudo apt-get update -q
  #- sudo apt-get install -q -y openjdk-8-jdk
  #- java -version
  #- sudo apt-get install -y maven
  #- mvn -version | head -n 1
  #- git clone https://github.com/airsonic/airsonic.git
  #- cd airsonic
  #- mvn clean package -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  #- ls -l ./airsonic-main/target/airsonic.war
  #- cd ..
  #- mkdir -p ./rootfs/usr/lib/airsonic
  #- mv ./airsonic/airsonic-main/target/airsonic.war ./rootfs/usr/lib/airsonic/.

before_script:
  - sed -i -e '/^$/d' -e 's/^[ \t]*//' -e '/^#/d' Dockerfile
  - chmod 0544 rootfs/usr/local/bin/*.sh

script:
  - >
    docker build
    --build-arg DOWNLOAD_URL="$DOWNLOAD_URL"
    --label org.label-schema.build-date="$BUILD_DATE"
    --label org.label-schema.build-number="$BUILD_NUMBER"
    --label org.label-schema.description="$DOCKER_DESCRIPTION"
    --label org.label-schema.maintainer="$DOCKER_MAINTAINER"
    --label org.label-schema.name="$DOCKER_NAME"
    --label org.label-schema.url="$DOCKER_URL"
    --label org.label-schema.version="$DOCKER_VERSION"
    --label org.label-schema.schema-version="$SCHEMA_VERSION"
    --label org.label-schema.vcs-ref="$VCS_REF"
    --label org.label-schema.vcs-url="$VCS_URL"
    --tag ${DOCKER_USERNAME}/${DOCKER_NAME}:${DOCKER_TAG}
    --pull .

after_success:
  - echo ${DOCKER_PASSWORD} | docker login --username ${DOCKER_USERNAME} --password-stdin
  - docker push ${DOCKER_USERNAME}/${DOCKER_NAME}:${DOCKER_TAG}

notifications:
  email:
    on_success: never
    on_failure: change
