language: bash
dist: trusty
sudo: required

before_install:
  - sudo apt-get update
  - sudo apt-get upgrade -y
  - docker version
  - if [ "${TRAVIS_BRANCH}" == "master" ]; then
      export DOCKER_TAG="latest";
    else
      export DOCKER_TAG=${TRAVIS_BRANCH};
    fi

install:
  - echo "building image ${DOCKER_IMAGE}:${DOCKER_TAG}"
  - echo `git remote get-url origin`
#  - >
#    docker build
#    --label org.label-schema.build-date=`date -u +"%Y-%m-%dT%H:%M:%SZ"`
#    --label org.label-schema.vcs-ref=`git rev-parse --short HEAD`
#    --tag ${DOCKER_USERNAME}/${DOCKER_IMAGE}:${DOCKER_TAG}
#    .

#after_success:
#  - >
#    docker login
#    --username ${DOCKER_USERNAME}
#    --password ${DOCKER_PASSWORD}
#  - docker push ${DOCKER_USERNAME}/${DOCKER_IMAGE}:${DOCKER_TAG}

notifications:
  email:
    on_success: change
    on_failure: change
#  slack:
#    rooms:
#      - stlouisn:${SLACK_API}#random
#    on_success: always
#    on_failure: always
