language: bash
dist: trusty
sudo: required

before_install:
  - sudo apt-get update
  - sudo apt-get upgrade -y
  - docker version
  - if [ "${TRAVIS_BRANCH}" == "master" ]; then
      export DOCKER_TAG="latest";
    else
      export DOCKER_TAG=${TRAVIS_BRANCH};
    fi
  - export SUBSONIC_VERSION=`curl -sS http://www.subsonic.org/pages/download.jsp | grep "standalone.tar.gz" | awk -F "-" '{print $2}'`

install:
  - docker build --build-arg SUBSONIC_VERSION=${SUBSONIC_VERSION} --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` --build-arg VCS_REF=`git rev-parse --short HEAD` -t ${DOCKER_USERNAME}/${DOCKER_IMAGE}:${DOCKER_TAG} .

after_success:
  - docker login --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD}
  - docker push ${DOCKER_USERNAME}/${DOCKER_IMAGE}:${DOCKER_TAG}

notifications:
  email:
    on_success: change
    on_failure: change
