version: '2.4'

services:

  airsonic:
    image: stlouisn/airsonic
    container_name: airsonic
    hostname: airsonic
    environment:
      - LC_ALL=C.UTF-8
      - TZ=UTC
    restart: always
    volumes:
      - /docker/airsonic/config:/config
      - /media/music:/music
      - /media/playlists:/playlists
      - /media/podcasts:/podcasts
    ports:
      - 4040:4040
