version: '2.3'

services:

  airsonic:
    image: stlouisn/airsonic:latest
    container_name: airsonic
    hostname: airsonic
    restart: always
    volumes:
      - ./airsonic/config:/var/lib/airsonic:rw
      - ./airsonic/music:/music:rw
      - ./airsonic/playlists:/playlists:rw
      - ./airsonic/podcasts:/podcasts:rw
    ports:
      - 4040
