version: '2.3'

services:

  subsonic:
    image: stlouisn/airsonic:latest
    container_name: airsonic
    hostname: airsonic
    environment:
      - TZ=UTC
      - LC_ALL=C.UTF-8
    restart: always
    volumes:
      - ./airsonic/config:/var/lib/airsonic:rw
      - ./airsonic/music:/music:rw
      - ./airsonic/playlists:/playlists:rw
      - ./airsonic/podcasts:/podcasts:rw
    ports:
      - 4040
