version: '2.2'

  subsonic:
    image: stlouisn/subsonic
    container_name: subsonic
    hostname: subsonic
    restart: always
    volumes:
      - ./subsonic/config:/var/lib/subsonic:rw
      - ./subsonic/music:/music:rw
      - ./subsonic/playlists:/playlists:rw
      - ./subsonic/podcasts:/podcasts:rw
