version: '2.3'

services:

  airsonic:
    image: stlouisn/airsonic:latest
    container_name: airsonic
    hostname: airsonic
    environment:
      - TZ=UTC
    restart: always
    volumes:
      - ./airsonic/config:/var/lib/airsonic:rw
      - ./storage/music:/music:rw
      - ./storage/playlists:/playlists:rw
      - ./storage/podcasts:/podcasts:rw
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - 4040
